[leia_pix]
YOUR_CLIENT_ID = "f71c1dfc-f759-45b5-9259-cf6705ffdadd"
YOUR_CLIENT_SECRET = "1nOo1Zmhw1uVmn3XvCxWQ6cD835gg9SI"



[passwords]
admin = "chicoosapo23"
emidiosouza = "noveadoiseujaganhei"

[google_cloud]
project_id = "f71c1dfc-f759-45b5-9259-cf6705ffdadd"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDatm3IRx0BZOFD\nH0jjFGId1HZRjOIwApaAhkKl2LmmHnBB/5nQoQ75pWejgw6MyIB28v7iBKyIclGR\nJxgVq1gleUm1X8cHEBO4uQQZACyvebcFyldeMdP97v8K5gREOdLejt8nmosa9xRo\na4dlnA3VRwzx3yy/ZnU4eX3FMsg3bPIBL6rPBfpRbAIfVMZU7bQy33671MAG7kn3\nh1XW/ZOUbtp5Mh8L/sD0sWOiR54xABR7XdKoPBNts9kPN02fvKUImjgmiKpAA2cr\nuKlnMehUQjvJsW5NucHTNUybJDxA39kbZ7Cw64mK4QC9e+PLRkDCYEkirvRdBZKv\ny6h4ujJ9AgMBAAECggEAF0E06InZJWwMwIaLyStCaHIN94tPhHPN/VHpNbmWubk8\nTeQnvmVVkok5/QqDCkiKUjtxiuYc0zA2iIS73Jf4mhlskyahIpjcw/QWIbNhTPIX\n2fuC8R7Cr9oQz5+X3go459WQmCUoO8CAML8YKR9f4Ci7EV+doic6ePv/+a7112Ch\ncBjHzOsVxuQBhQiZbZ7noez+wexlCWDD95RaHgnZZXyzLCZg3yakPkKUyjUaGLRi\nAjyxDIy++YBdUFI5HO7XY0iRXyWIYmA/2COKRNqTxs1hLnKuZc6GZ9iPjRg0CfGl\nVtfKk3RO//NdYnACV/fL9y9bnRknE8ZeTS3DUgsdSQKBgQD6KbAChSx3y8hvCuNA\ncUUemgIKW2UAC56J/Cv21mwWKSgX69jseWWu8P0Y6PC/6BEJr5slVKHeg68T31Zm\nirnf+FRHLjvS5bn6kVpH7O8gRV/AoN4TjwoiL2/1j2IMiHuPFeCYihs5X977YWVr\nDUiAY/4k5gRNSaWRfUJm7xv86QKBgQDf0OC2w+EbgmehZ//y3VrbDoE8PnK+3D9h\nL1trQiWhHbgEfkixMs/n44KCjiOr/QifVSv8QjSK2o7NTJ/stNnCIQ4Q8UllWUDU\nIDNTwCkiLlhYuU/wXG7UBhVJK+6GO6Zqm9F97OaBL3ek1nT9BLTyvxWdSASge96H\nGxz/hsE8dQKBgHfN4ycx1BwDEhhr5G2GUY3YP8XqAzLEXcbDZ+KsydLLHxJlttt5\nQANKEkwNss6VOyOiX/C+2U6RThV8TgqJwX7LlMEKGUhlEG45kj0D8XlJABRmdjRz\numyovzug0VojOtlJpugmq+cMTOOiv0lHcUNbn+jX55OEA7DrhhN5y7ORAoGAfE9X\ngCtrbAwR4uQQlKO9Qs3bmcpVkQxjZ2cWL4yduc731gcN+N1v/Cuw4TJxPaVclKKJ\nu6JJ7JVXm09jw+TuzZPubBqX2WKpTyhTWcDxF7sF9sF2VNoB9GEskWeFI6kd1TiW\nMorRvA7RNQyoDZ//oJPhPWoyp7Ak+IVmpcYCrcECgYBnWQZIOzgXcfUR5Oj3KN8C\nvOTnV3dUlbHT0CxZzYbsdsfwFCQ1mQZ8buTznbdmdR/0hKrENxfckG417IFPFzVY\nJxEs/Ut3PG3myiPvBfH///rQNFeK8W6OU/RIKqHnBeC+s1kTCY9Y13BOb0HYg2h5\ni/s0IIDUsxnPpRa5IBkwTA==\n-----END PRIVATE KEY-----\n"
client_email = "speck-leia@speck-animator.iam.gserviceaccount.com"
client_id = "109032283235012185632"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/speck-leia%40speck-animator.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
GOOGLE_CLOUD_BUCKET_NAME = "speck_leia"
